import { Event } from "../models/Event";

export const events: Event[] = [
  {
    id: 0,
    responses: 8,
    score: 0,
    host_first_name: "Daniel",
    host_last_name: "Noon",
    host_email: "danielanoon@outlook.com",
    date_time: "2021-03-08T04:01:28.910Z",
    description: "A test event",
    location: "Here",
    title: "Incomplete Event",
    invitees: 24,
    food_buffet: false,
    food_prepackaged: true,
    host_id: 0,
    indoor: false,
    outdoor: true,
    remote: false,
  },
  {
    responses: 12,
    host_first_name: "Author",
    host_last_name: "Name",
    host_email: "author@example.com",
    date_time: "2021-03-08T04:01:28.910Z",
    description: "Event description...",
    location: "Here",
    title: "Event Title",
    invitees: 20,
    id: 1,
    food_buffet: true,
    food_prepackaged: false,
    host_id: 2,
    indoor: false,
    outdoor: true,
    remote: false,
    score: 0,
  },
  {
    responses: 5,
    host_first_name: "Author",
    host_last_name: "Name",
    host_email: "author@example.com",
    date_time: "2021-03-08T04:01:28.910Z",
    description: "Event description...",
    location: "Here",
    title: "Event Title",
    invitees: 20,
    id: 2,
    food_buffet: false,
    food_prepackaged: true,
    host_id: 2,
    indoor: true,
    outdoor: false,
    remote: false,
    score: 0,
  },
  {
    score: 3.3,
    responses: 9,
    host_first_name: "Author",
    host_last_name: "Name",
    host_email: "author@example.com",
    date_time: "2021-03-08T04:01:28.910Z",
    description: "Event description...",
    location: "There",
    title: "Created Event",
    invitees: 10,
    id: 3,
    food_buffet: false,
    food_prepackaged: true,
    host_id: 2,
    indoor: true,
    outdoor: false,
    remote: false,
  },
  {
    score: 1.2,
    host_first_name: "Author",
    host_last_name: "Name",
    host_email: "author@example.com",
    date_time: "2021-03-08T04:01:28.910Z",
    description: "Event description...",
    location: "There",
    title: "Event Title",
    invitees: 10,
    id: 4,
    food_buffet: true,
    food_prepackaged: false,
    host_id: 2,
    indoor: true,
    outdoor: false,
    remote: false,
    responses: 10,
  },
  {
    score: 4.5,
    host_first_name: "Author",
    host_last_name: "Name",
    host_email: "author@example.com",
    date_time: "2021-03-08T04:01:28.910Z",
    description: "Event description...",
    location: "There",
    title: "Event Title",
    invitees: 10,
    id: 5,
    responses: 10,
    food_buffet: false,
    food_prepackaged: true,
    host_id: 2,
    indoor: true,
    outdoor: false,
    remote: false,
  },
  {
    score: 4.3,
    host_first_name: "Nathan",
    host_last_name: "Gentry",
    date_time: "2021-03-08T04:01:28.910Z",
    description:
      "Get ready to celebrate with Alicia to help her kick off her 25th year! Just because we are masking up doesn’t mean we have to shut down the party 🎉\n\nRemember to bring your dancing shoes cause we’re gonna be dancing the night away 💃",
    location: "123 Main St.",
    title: "Alicia's Birthday Bash",
    invitees: 12,
    id: 6,
    host_email: "nathan@nathangentry.me",
    responses: 10,
    food_buffet: false,
    food_prepackaged: true,
    host_id: 1,
    indoor: false,
    outdoor: true,
    remote: false,
  },
  {
    score: 2.7,
    host_first_name: "Author",
    host_last_name: "Name",
    date_time: "2021-03-08T04:01:28.910Z",
    description: "Event description...",
    location: "There",
    title: "Event Title",
    invitees: 10,
    id: 7,
    host_email: "author@example.com",
    responses: 10,
    food_buffet: false,
    food_prepackaged: true,
    host_id: 2,
    indoor: true,
    outdoor: false,
    remote: false,
  },
  {
    score: 5.0,
    host_first_name: "Daniel",
    host_last_name: "Noon",
    id: 8,
    host_email: "danielanoon@outlook.com",
    date_time: "2021-03-08T04:01:28.910Z",
    description: "A test event",
    location: "Here",
    title: "Incomplete Event",
    invitees: 24,
    responses: 15,
    food_buffet: false,
    food_prepackaged: true,
    host_id: 0,
    indoor: false,
    outdoor: true,
    remote: false,
  },
  {
    score: 1.2,
    host_first_name: "Daniel",
    host_last_name: "Noon",
    host_email: "danielanoon@outlook.com",
    date_time: "2021-03-08T04:01:28.910Z",
    description: "Event description...",
    location: "There",
    title: "Event Title",
    invitees: 10,
    id: 9,
    responses: 10,
    food_buffet: false,
    food_prepackaged: true,
    host_id: 0,
    indoor: false,
    outdoor: true,
    remote: false,
  },
  {
    score: 1.2,
    host_first_name: "Daniel",
    host_last_name: "Noon",
    date_time: "2021-03-08T04:01:28.910Z",
    description: "Heck yeah it's maskless time",
    location: "There",
    title: "Uncomfortable Event",
    invitees: 10,
    id: 10,
    responses: 10,
    food_buffet: false,
    food_prepackaged: true,
    host_email: "danielanoon@outlook.com",
    host_id: 0,
    indoor: false,
    outdoor: false,
    remote: true,
  },
];
